### PR TITLE
Fix the Fluidic Compressor, fixed triggers and added a mode switch actio...

### PR DESCRIPTION
**Pull request by iTitus**
...n.

### CODE REVIEW

**Comment by iTitus** [comment]
Waiting for textures from @Plenituz...

**Comment by AEnterprise** [comment]
textures are in the dropbox, will be pulling and merging later today or tomorow

**Comment by iTitus** [comment]
Thanks

**Comment by iTitus** [comment]
Finished with textures: less work for you :D

**Comment by AEnterprise** [comment]
also merged

**Pull request closed without merging**
