### PR TITLE
Created the base for ownable machines. They will save the UUIDs, so that...

### PR DESCRIPTION
**Pull request by iTitus**
... they support name changes.

### CODE REVIEW

**Comment by iTitus** [comment]
In favor of #258 ;)

**Comment by AEnterprise** [comment]
not gona merge this yet, i sugest you continue with this and implement the whole thing? i'll still do bugfixes for BCA but also gona work a bit on eureka so as you already started on this i sugest you do all of it if you want?

**Comment by iTitus** [comment]
That was how i thought it should work. This is for feedback and suggestions ;)

**Comment by AEnterprise** [comment]
with all of these 'merge master branch' commits in it i do need to ask you to squash all of it when you are done

**Comment by iTitus** [comment]
I will squash once finished ;)

**Comment by iTitus** [comment]
Finished. Anything more to do?

**Comment by AEnterprise** [comment]
yes you should give me time to review this (will do that tomorow)

**Comment by iTitus** [comment]
Well I meant content ;)

**Comment by AEnterprise** [comment]
won't know that till i reviewed it

**Pull request closed without merging**
