### PR TITLE
Achievements

### PR DESCRIPTION
**Pull request by iTitus**

### CODE REVIEW

**Comment by iTitus** [comment]
Progress:
Progress

**Comment by iTitus** [comment]
More Progress:
More Progress

**Comment by AEnterprise** [comment]
squach them please, "more progress" is no good commit message, if you wana use a message like that at least specify what you are working on

**Comment by iTitus** [comment]
@AEnterprise It will be squashed ;)

**Comment by iTitus** [comment]
Even more progress

**Comment by AEnterprise** [comment]
that's ALOT of achievements

**Comment by iTitus** [comment]
Oh yeah. I will need someone creative to write names and descriptions for each of them :P

**Comment by AEnterprise** [comment]
ok but it does look a bit overkill to me atm :P

**Comment by leSamo** [comment]
Roses are red, violets are blue, you need somebody creative, so here I am for you.

**Comment by leSamo** [comment]
What do you think?
achievement.basicDusterCrafting.name=Rolling Stones
achievement.semiAutomaticDusterCrafting.name=Hop, hop, hopper
achievement.powerCapsuleTier1Crafting.name=Not suitable for children under age of 3
achievement.blazeStickPickup.name=Don't forget your gloves
achievement.chargingStationCrafting.name=Pikachu in box
achievement.pipeColoringToolCrafting.name=True artist
achievement.portableLaserPickup.name=They said dreams don't come true

**Comment by AEnterprise** [comment]
sounds very good

**Comment by leSamo** [comment]
What's the achievement description unlocalized name? achievement.[achievementName].desc.name?

What I've got so far - http://pastebin.com/YY3XV3Nh.

**Comment by iTitus** [comment]
I like it ;)
 The formats are:
- achievement.bca.[achievementName]
- achievement.bca.[achievementName].desc

Atleast that's what I can see in code.

**Comment by leSamo** [comment]
Here you are - http://pastebin.com/DMhsSU4V
Am gonna do the desc tommorow, I have to go. And if I fail test tommorow I'll blame you.

**Comment by iTitus** [comment]
Thank you ;)
Good luck for your test...

**Comment by BigXplosion** [comment]
I'm loving the names so far though! :D

**Comment by leSamo** [comment]
Am glad you like it <3

**Comment by leSamo** [comment]
Updated Achievement names also with descriptions!
http://pastebin.com/wc5v5Amu
If you ever need help with something again, feel free to ask me.

**Comment by AgentK9** [comment]
AWESOME!!!!!

**Comment by AlexTheGre4t** [comment]
If this happens, it could be a good idea to incorporate the eureka alerts with achievement popups, might look better than in the chat.

**Comment by AEnterprise** [comment]
sounds like a good idea but not like that, i could do this in eureka itself and replace the chat message with a acievement popup (like thaumcraft does)

**Comment by BigXplosion** [comment]
that would be exactly the same thing I thought, but then I would turn of the achievements if Eureka is detected. If you don't do this you will have the pop-up twice at the same time + you get an achievement and a eureka thingy that seems like 2 times the same thing (although it isn't)

**Comment by leSamo** [comment]
I agree with @BigXplosion. If you don't have Eureka you'll have achivements like craft a mechanical duster. If you have it you'll have Eureka progress w/ pup-up "achievements" (objective completition) like dust 20 ores w/ mechanical duster.
SFMBE

**Comment by iTitus** [comment]
I will probably make a config option.

**Comment by AEnterprise** [comment]
maybe you should also look up the git config option to rebase instead of merge when pulling

**Comment by iTitus** [comment]
I fixed my workspace, finally ;)

**Comment by AEnterprise** [comment]
congrats, but could you join me on irc before working more on this?

**Pull request closed without merging**
