### PR TITLE
Fixed some potential Container bugs and moved the phantom slot logic to ...

### PR DESCRIPTION
**Pull request by iTitus**
...the SlotPhantom class.

Will allow some more advanced SlotPhantoms soon(tm).

### CODE REVIEW

**Comment by BigXplosion** [comment]
Thanks @iTitus, I was just about to push itemSorter stuff so yeah It would be annoying to have merge conflicts :D

**Comment by iTitus** [comment]
Was ill :(

**Comment by iTitus** [comment]
I am better now, so I finished some code :P

**Comment by iTitus** [comment]
Squashed :D

**Comment by BigXplosion** [comment]
if you tell me that this code worked in the ItemSorter GUI then this looks good to me!

**Comment by iTitus** [comment]
It worked perfectly. After I fixed my derp. I tested it with the wrong slots...
Although there are a few weirdnesses (which were also there before).

**Comment by BigXplosion** [comment]
ok nice, I'll see when it gets accepted

**Comment by AEnterprise** [comment]
merged

**Pull request closed without merging**
