### PR TITLE
Nei recipe handling system for the Refinery and cooling tower.

### PR DESCRIPTION
**Pull request by BigXplosion**
I'll clean up the duster one after @AlexTheGre4t's PR for the texture is merged.

### CODE REVIEW

**Comment by iTitus** [comment]
Looks very nice:
Just a minor thing: while the fluid is moving inside the tanks there is a moment where there is no fluid in the tank, causing the tooltip to vanish.
Maybe the ratio of conversion wouldn't be that bad too.

**Comment by BigXplosion** [comment]
is it that bad? not sure what the best way is to fix that

**Comment by AEnterprise** [comment]
the tooltip is indeed something that would be nice to have fixed

**Comment by AEnterprise** [comment]
can you make this available from the cooling tower and refinery gui's?

**Pull request merged**
