### PR TITLE
Made some minor changes to mcmod.info.

### PR DESCRIPTION
**Pull request by KamranMackey**

### CODE REVIEW

**Comment by AEnterprise** [comment]
calling in @BigXplosion and @iTitus to see if they agree

**Comment by KamranMackey** [comment]
@AEnterprise Alright. Hopefully they will. :smiley:

**Comment by iTitus** [comment]
I approve :D

**Comment by BigXplosion** [comment]
same

**Comment by AEnterprise** [comment]
i merge

**Pull request merged**
