### PR TITLE
alternate recipe for dusters that require a slimeball (configurable)

### PR DESCRIPTION
**Pull request by BigXplosion**
still needs texture. I don't know how I forgot about this but I got this PR ready like a week ago....

### CODE REVIEW

**Comment by AEnterprise** [comment]
gona wait merging till we have texture

**Comment by BigXplosion** [comment]
sure, I just had this laying around for a while =D

**Comment by leSamo** [comment]
1. Did you mean "alternate recipe for dusters that DOESN'T require a slimeball (configurable)"?
2. This is a really good idea, because getting slimeballs is sometimes a pain in the butt.
3. Although I think it should be disabled by default, because 3 iron is nothing compared to a slimeball.
4. Recipe might use iron wire or iron wire (unhardened), that would make more sense.
5. Iron Spring texture: http://i.imgur.com/fEa6lNK.png

**Comment by BigXplosion** [comment]
@leSamo yeah not sure what to configure it too but I can't use iron wire for it as iron wire requires a dust to make :D

**Comment by leSamo** [comment]
Oh yea... *derp*

**Comment by leSamo** [comment]
Do you like the texture?

**Comment by AEnterprise** [comment]
merge conflicts

**Comment by AEnterprise** [comment]
closing and doing it myself

**Pull request closed without merging**
