### PR TITLE
new compat system

### PR DESCRIPTION
**Pull request by BigXplosion**
this is the new compat system (yaay). All the stuff seems to be loaded, but there might still be some bugs which can only be found when trying this out, I know that this might be annoying but I can't test out every feature currently in the modules. But it doesn't crash atleast.

### CODE REVIEW

**Comment by AEnterprise** [comment]
looking good

**Comment by Speiger** [comment]
I have already a bugreport on this way.
Its a great idea. And close to beeing perfect. But when you setup the module you newinstance them and if classes are missing that will cause a crash. That simply means you do rely on all these mods in your mod.
To solve that is to load modules via classpath and he trys to load them with newinstance them in a safe area (in a try catch) so then it can crash but giving only a report. 

I copied that system from the old IC2 (1.4.7) and it works fine. Even if you delete the Folders (i made that system with folders so i have everything sortet) nothing crashes. So you are able to delete modintigration also.

https://github.com/TinyModularThings/TinyModularThings/blob/1.6.4/Spmod_Common/Source/speiger/src/tinymodularthings/common/plugins/PluginLoader.java

Also if you have compats that are client sided only you should use sidedProxies on the compatloader so you can split them.

**Comment by AEnterprise** [comment]
you do have a point there, i'll make it use class referneces later

**Comment by Speiger** [comment]
Ok.

**Pull request merged**
