### PR TITLE
Fix CompatMetals, tweaked a few recipes, added Dark Iron and added log m...

### PR DESCRIPTION
**Pull request by iTitus**
...essages to the DusterRecipeManager.

### CODE REVIEW

**Comment by AEnterprise** [comment]
are the logger messages realy needed? won't they just spam the console and logs?

**Comment by iTitus** [comment]
The are very handy to find out what's happening.

**Comment by iTitus** [comment]
Related to ganymedes01/Another-One-Bites-the-Dust#47

**Comment by iTitus** [comment]
Finished

**Comment by AEnterprise** [comment]
merged in https://github.com/BCA-Team/Buildcraft-Additions/commit/481ae2da4af01c14cb9b4cc1185099744b71ba5e

**Pull request closed without merging**
