### PR TITLE
Should fix #429

### LINKED ISSUE #429: BCA 2.2 beta missing Iron Canister recipe

### PR DESCRIPTION
**Pull request by leSamo**

### CODE REVIEW

**Comment by AEnterprise** [comment]
ah, derp on my part, thanks for the fix but could you sign the CLA first?
https://www.clahub.com/agreements/BCA-Team/Buildcraft-Additions

**Comment by leSamo** [comment]
"We're sorry, but something went wrong."

**Comment by AEnterprise** [comment]
very odd, can you try again in a few mins? might be something on the clahub side

**Comment by leSamo** [comment]
Ok, It's signed I suppose.

**Comment by leSamo** [comment]
It's signed, you can merge it.

**Comment by AEnterprise** [comment]
unless i'm going blind i don't see you name on the list

**Comment by leSamo** [comment]
dasda

**Comment by AEnterprise** [comment]
wrong agreement, folow the link i linked you, that's the old one

**Comment by leSamo** [comment]
"We're sorry, but something went wrong."

**Pull request merged**
